name: Run compiled MATLAB executable
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MATLAB
        id: setup-matlab
        uses: matlab-actions/setup-matlab@v2
        
      - name: Run executable
        run: |
          ./run_magicsquare.sh ${{ steps.setup-matlab.outputs.matlabroot }} 5